name: 🧭 Epic
description: Umbrella issue that tracks a milestone with multiple sub-issues
title: "🧭 "
labels: ["kind:epic"]
assignees:
  - davilivob
projects: ["2enter/3"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What’s the goal of this epic?
      placeholder: |
        **Goal:**
        -

        **Why:**
        -

        **Non-goals:**
        -
    validations:
      required: true
