name: Feature request
description: Suggest an idea
title: "Name me"
labels: ["kind:feature"]
assignees:
  - davilivob
projects: ["2enter/3"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: false
