name: ✨ Feature request
description: Suggest an idea
title: "✨ "
labels: ["kind:feature", "effort:easy", "prio:important"]
assignees:
  - davilivob
projects: ["2enter/3"]
body:
  - type: textarea
    id: needs
    attributes:
      label: Needs
      description: List the key elements of this feature.
      placeholder: |
        1.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes / links
      description: Some notes or links related to this feature.
      placeholder: |
        - [example code](https://example.com)
    validations:
      required: false

  - type: textarea
    id: related
    attributes:
      label: Related
      description: List other issues or pull requests that this feature is related to.
      placeholder: |
        1. #

        **Depends on**
        1. #
    validations:
      required: false
