name: Feature request
description: Suggest an idea
title: "[feature] "
labels: ["kind:feature", "effort:easy", "prio:important"]
assignees:
  - davilivob
projects: ["2enter/3"]
body:
  - type: textarea
    id: needs
    attributes:
      label: Needs
      description: List the key elements of this feature.
      placeholder: |
        1.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
    validations:
      required: false

  - type: textarea
    id: docs
    attributes:
      label: Documentations
      description: External documentation links.
      placeholder: |
        - [example code](https://example.com)
    validations:
      required: false

  - type: textarea
    id: depends_on
    attributes:
      label: Depends on
      description: List other issues or pull requests that this feature depends on.
      placeholder: |
        1. #
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the impact of this feature on the project.
      placeholder: |
        1. #
    validations:
      required: false
