name: Feature request
description: Suggest an idea
title: ""
labels: ["kind:feature"]
assignees:
  - davilivob
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: prio
      options:
        - important
        - medium
        - hard
      default: 1
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - easy
        - medium
        - hard
      default: 1
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - Core
        - Extra
    validations:
      required: false
