name: Feature request
description: Suggest an idea
title: "f"
labels: ["kind:feature"]
assignees:
  - davilivob
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - prio:critical
        - prio:important
        - prio:later
      default: 1
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Effort
      options:
        - effort:easy
        - effort:medium
        - effort:hard
      default: 1
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - scope:core
        - scope:extra
    validations:
      required: false
